# Generated by Django 3.2.12 on 2022-02-11 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
            ],
            options={
                'db_table': 'advert_video',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='AdvertVideoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_video', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Successfully finished'), ('ERROR', 'Error')], default='NOT_STARTED', max_length=100)),
                ('separate_audio', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Successfully finished'), ('ERROR', 'Error')], default='NOT_STARTED', max_length=100)),
                ('advert_entry', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Successfully finished'), ('ERROR', 'Error')], default='NOT_STARTED', max_length=100)),
                ('send_acr_cloud', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Successfully finished'), ('ERROR', 'Error')], default='NOT_STARTED', max_length=100)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adverts.advertvideo')),
            ],
            options={
                'db_table': 'advert_video_status',
            },
        ),
        migrations.AddField(
            model_name='advertvideo',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.brand'),
        ),
    ]
