# Generated by Django 3.2.12 on 2022-02-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertvideostatus',
            name='advert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='adverts.advertvideo'),
        ),
    ]
