# Generated by Django 3.2.12 on 2022-02-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_advertvideostatus_advert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertvideostatus',
            old_name='advert_entry',
            new_name='convert_video_to_wav',
        ),
        migrations.RenameField(
            model_name='advertvideostatus',
            old_name='send_acr_cloud',
            new_name='split_audio_files',
        ),
        migrations.RemoveField(
            model_name='advertvideostatus',
            name='separate_audio',
        ),
    ]
