# Generated by Django 3.2.12 on 2022-03-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_advertvideostatus_send_acr_cloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.advertvideo')),
            ],
            options={
                'db_table': 'advert_task',
            },
        ),
    ]
