# Generated by Django 3.2.12 on 2022-03-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_advertvideostatus_musiio'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertvideostatus',
            name='chartmetric',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Successfully finished'), ('ERROR', 'Error')], default='NOT_STARTED', max_length=100),
        ),
    ]
