# Generated by Django 3.2.12 on 2022-03-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0009_advertvideostatus_neural_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverttask',
            name='advert_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
