# Generated by Django 3.2.12 on 2022-03-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0010_adverttask_advert_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverttask',
            name='advert_url',
        ),
        migrations.AddField(
            model_name='advertvideo',
            name='advert_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
